### ISSUE TITLE
Mise à jour

### ISSUE THREAD

**Issue by quark67** [Karnaj/cours-ruby#6]
Merci de bien vouloir supprimer ma contribution à 3-1-2_OS X - TextWrangler.md sur ZdS, puisque j'y suis désormais indésirable (compte bloqué sous prétexte fallacieux).

**Comment by Karnaj** [comment]
Ok. Le banissement est définitif ?

**Comment by quark67** [comment]
D'après le mail reçu, oui. Je ne voudrais pas polluer Github avec les détails, donc peux-tu m'écrire à <mon nom> chez free.fr ? Je t'enverrais une copie de ce qui m'a été envoyé, avec la phrase litigieuse, mais aussi un lien vers un article de Wikipédia, qui semble montrer que je ne suis pas en tort, malgré ce qu'en pense SpaceFox, auteur du ban. Je ne me battrais pas pour une réintégration à ZdS, puisque ce site semble hélas gangréné par des modos qui m'ont dans le pif. Dernière demande, peux-tu indiquer à Dominus Canufex que mon ban définitif m'empêche de répondre à son dernier message privé ? De même, merci d'indiquer à Abrahan que je ne pourrais plus l'aider dans son sujet : https://zestedesavoir.com/forums/sujet/4614/image-au-contour-flou/ (comme il pose souvent des questions sur LaTeX, tu peux lui indiquer aussi le nouveau site http://texnique.fr qui est un stackoverflow français consacré à LaTeX ; NB : qu'il lise bien la FAQ http://texnique.fr/osqa/faq/ et notamment http://texnique.fr/osqa/faq/#custom-id-contributions-utiles ). 

:(

**Comment by quark67** [comment]
Le lien de contact est mal passé. Je remet : `mon nom` chez free.fr.

**Comment by Karnaj** [comment]
C'est fait. Dominus Carnufex m'a donné son adresse mail pour que tu puisses lui répondre. Je te l'envoie par mail.

**Comment by quark67** [comment]
Je n'ai rien reçu encore. As-tu bien envoyé à la bonne adresse ? Rappel :  `mon_pseudo` chez `free.fr`. Merci.

**Comment by Karnaj** [comment]
Je l'ai renvoyé. Toujours rien reçu ?

**Comment by quark67** [comment]
Rien :(. Peux-tu indiquer avec quelle adresse tu envoies ? Je n'ose imaginer que tu utilises hotmail, mais j'ai le souvenir de difficultés entre hotmail et free à l'époque où hotmail était pas mal utilisé. On est peut-être dans un cas similaire. L'autre hypothèse serait que tu as mal décodé `mon_pseudo` chez `free.fr`. 

Sinon, si tu emploies l'IRC, il y a possibilité de se contacter soit sur le canal de ZdS (voir https://zestedesavoir.com/forums/sujet/500/zestedesavoir-sur-smoothirc-le-canal-irc-de-zeste-de-savoir/) si je ne m'y fais pas éjecter, soit sur un autre à ta convenance, en me prévenant à l'avance lorsque tu t'y trouveras (si c'est pas sous le pseudo 'Karnaj', merci de donner celui employé).

**Comment by quark67** [comment]
J'ai reçu ton mail ce matin à 3 heures. J'ignore quand tu l'as envoyé. Pourrais-tu me l'indiquer, afin que je puisse déterminer si effectivement il y a un problème entre Hotmail et Free ? Mon courrielleur a de surcroît par défaut affiché ton mail comme « indésirable ». Je suppose qu’Hotmail n'a décidément pas bonne presse. Merci en tout cas.

**Comment by Karnaj** [comment]
Je l'ai renvoyé hier puisque le premier n'était pas arrivé.
